name: Release
on:
  push:
    branches: [release]
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']
env:
  NODE_VERSION: 10.22

jobs:
  push_new_tags:
    name: push new tags
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      COMMIT: ${{github.sha}}
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{env.NODE_VERSION}}
    - run: node ci/pushNewTag
  
  build_beta: 
    name: build beta
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hmarr/debug-action
