name: Release
on:
  push:
    branches: [release]
env:
  NODE_VERSION: 10.22

jobs:
  push_new_tags:
    name: push new tags
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      COMMIT: ${{github.sha}}
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.TEST_TOKEN}}
    - uses: actions/setup-node@v1
      with:
        node-version: ${{env.NODE_VERSION}}
    - run: node ci/pushNewTag