name: Master

on:
  push:
    branches: ['master']

env:
  NODE_VERSION: 10.22

jobs:
  test:
    name: 'test'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    steps:
    - uses: actions/checkout@v2
    - run: 

