name: Beta

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

env:
  NODE_VERSION: 10.22

jobs:
  test:
    name: 'test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    

